from fpdf import FPDF
import os

class LetterPDF(FPDF):
    def header(self):
        # We don't want a repeating header on every page for standard letters
        pass

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by VerbaPost", 0, 0, "C")

def create_pdf(body_text, recipient_str, sender_str, is_heirloom=False, sig_path=None):
    """
    Generates a clean, professional PDF letter.
    """
    pdf = LetterPDF()
    pdf.set_margins(25, 25, 25) # Standard 1-inch margins
    pdf.add_page()
    
    # --- 1. FONTS ---
    # Setup fonts based on tier
    if is_heirloom:
        # Try to load a fancy font if available, else standard serif
        # Ensure these .ttf files exist in your root if you use them
        try:
            pdf.add_font("Heirloom", "", "GreatVibes-Regular.ttf", uni=True)
            main_font = "Heirloom"
            main_size = 14
        except:
            main_font = "Times"
            main_size = 12
    else:
        # Standard Civic/Business look
        main_font = "Arial" 
        main_size = 11

    # --- 2. SENDER ADDRESS (Return Address) ---
    # Top Left, smaller font
    pdf.set_font("Arial", "", 10) 
    # Split lines to ensure clean printing
    for line in sender_str.split('\n'):
        if line.strip():
            pdf.cell(0, 5, line.strip(), ln=True)
    
    pdf.ln(10) # Space between sender and recipient

    # --- 3. RECIPIENT ADDRESS ---
    # Standard Left align, slightly separate block
    pdf.set_font("Arial", "B", 11) # Bold Name only? Or all? Let's keep standard.
    # Actually standard letters are usually plain text for address.
    pdf.set_font("Arial", "", 11)
    
    for line in recipient_str.split('\n'):
        if line.strip():
            pdf.cell(0, 5, line.strip(), ln=True)

    # --- 4. DATE (Optional, but good practice) ---
    # If you want a date, uncomment the next lines:
    # import datetime
    # pdf.ln(5)
    # pdf.cell(0, 5, datetime.date.today().strftime("%B %d, %Y"), ln=True)

    pdf.ln(15) # Space before body starts

    # --- 5. THE BODY ---
    # Here is where the error likely was (printing address as title). 
    # We strictly print ONLY the body_text here.
    
    pdf.set_font(main_font, "", main_size)
    
    # Fix for standard FPDF handling of unicode/latin-1
    # We encode/decode to ensure compatibility if using standard fonts
    try:
        clean_body = body_text.encode('latin-1', 'replace').decode('latin-1')
    except:
        clean_body = body_text

    pdf.multi_cell(0, 6, clean_body)
    
    pdf.ln(15) # Space before signature

    # --- 6. SIGNATURE ---
    # "Sincerely,"
    pdf.cell(0, 6, "Sincerely,", ln=True)
    pdf.ln(10) # Space for signing
    
    # If a digital signature image exists, place it
    if sig_path and os.path.exists(sig_path):
        # x position matches margin (25), y is current y
        # w=50mm width (adjust as needed)
        pdf.image(sig_path, x=25, w=40)
        pdf.ln(5) # Adjust based on image height
    
    # Print the sender's name below the signature space
    sender_name = sender_str.split('\n')[0] # Extract first line (Name)
    pdf.cell(0, 6, sender_name, ln=True)

    # Output to byte string
    return pdf.output(dest="S").encode("latin-1")