from fpdf import FPDF
import os

class LetterPDF(FPDF):
    def header(self):
        pass # No header for standard letters

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by VerbaPost", 0, 0, "C")

def create_pdf(body_text, recipient_str, sender_str, is_heirloom=False, sig_path=None):
    pdf = LetterPDF()
    pdf.set_margins(25, 25, 25)
    pdf.add_page()
    
    # 1. Fonts
    if is_heirloom:
        try:
            pdf.add_font("Heirloom", "", "GreatVibes-Regular.ttf", uni=True)
            main_font = "Heirloom"
            main_size = 14
        except:
            main_font = "Times"
            main_size = 12
    else:
        main_font = "Arial"
        main_size = 11

    # 2. Sender (Top Left)
    pdf.set_font("Arial", "", 10)
    for line in sender_str.split('\n'):
        if line.strip():
            pdf.cell(0, 5, line.strip(), ln=True)
    
    pdf.ln(10)

    # 3. Recipient (Standard Block)
    # Removing 'B' (Bold) ensures it looks like a standard letter
    pdf.set_font("Arial", "", 11)
    for line in recipient_str.split('\n'):
        if line.strip():
            pdf.cell(0, 5, line.strip(), ln=True)

    pdf.ln(15)

    # 4. Body
    pdf.set_font(main_font, "", main_size)
    
    try:
        clean_body = body_text.encode('latin-1', 'replace').decode('latin-1')
    except:
        clean_body = body_text

    pdf.multi_cell(0, 6, clean_body)
    
    pdf.ln(15)

    # 5. Signature
    pdf.cell(0, 6, "Sincerely,", ln=True)
    pdf.ln(10)
    
    if sig_path and os.path.exists(sig_path):
        pdf.image(sig_path, x=25, w=40)
        pdf.ln(5)
    
    sender_name = sender_str.split('\n')[0]
    pdf.cell(0, 6, sender_name, ln=True)

    return pdf.output(dest="S").encode("latin-1")